### PR TITLE
Mark do-not-port

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Out of interest as to how much of the test-writing effort would be translatable to the new forms I went through & annotated all the lines I would not expect to be the same with the angular forms. (no need to merge - it's just for interest)

### CODE REVIEW

**Comment by xurizaemon** [comment]
Thanks! Yeah I think we should say "this is what the form _ought_ to look like", then write tests for that, then make 4.7 work against those tests. Which hopefully in 4.7 is a matter of adding some sane selectors - once we decide what they are.

**Comment by eileenmcnaughton** [comment]
TBH  I think to make the existing forms use the selectors we think they should and the form flow we think they should is a larger task than replacing them with angular forms

**Comment by xurizaemon** [comment]
It probably is. What else could we do then, include a big mapping of `email
=> email-5`?

**Comment by eileenmcnaughton** [comment]
Well - if we take the default option as being 'write new tests in one of the end-to-end frameworks that we select for the new angular forms' - then the idea of writing tests for QuickForm & then porting them to the new forms needs to be either easier or better. I think the argument that it is better is that the edge cases that currently exist can be captured and locked in - but another way of doing that would be to document them as a spec. I think there is also an argument being made that doing if for QuickForm is a necessity & having done that it would be easier to port them than to write fresh for angular forms - but this example does not support that argument

**Comment by xurizaemon** [comment]
Spec : thumbsup:

My concern atm is that the proposed "spec" for Big Swap seems to be "status quo", and I don't think anyone really knows what that is. I've seen this on paying work too :grin:

So I guess part of my intent here was to support those who want to spec out status quo by giving them (one more, probably the wrong) tool to do it with, as well as to show how easy it can be for other shops to use this.

It may be that more fleshed out examples do look more like they should be ported than written fresh. Eg we have one currently which tests com.AGH.giftMEMBERSHIPS which transitions through multiple webforms, contribute forms, & logged in/out states. That test may look very similar after Big Swap except for the form ids.

**Comment by xurizaemon** [comment]
PS. Sometimes I feel like we're disagreeing when you and I are just phrasing things differently ... I'd be keen to catch you in IRC or HipChat today to hear your thoughts on this and get a feeling for whether this is one of those times :D

**Pull request closed without merging**
